### ISSUE TITLE
/api/deck/:id response should contain the deck ID

### ISSUE THREAD

**Issue by Rylius** [tjhorner/cah-creator#1]
Makes working with the response a little easier as I don't have to add the ID manually.

**Comment by tjhorner** [comment]
:+1: will add when I get home, I was actually going to do this tonight; you read my mind!

**Comment by tjhorner** [comment]
Added in c4cdcacd4d77b201df8602616646d2a85cec758d

**Comment by tjhorner** [comment]
why
![image](https://cloud.githubusercontent.com/assets/2646487/10622958/a24029d8-773f-11e5-8864-f5cc7e3b5682.png)
